# Generated by Django 5.1.6 on 2025-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='check_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='entry',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='payee',
            field=models.CharField(default='', max_length=100),
        ),
    ]
