# Generated by Django 5.1.6 on 2025-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_check_number_entry_comment_alter_entry_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='payee',
            field=models.CharField(max_length=100),
        ),
    ]
